In [135]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [136]:
env=gym.make("FrozenLake-v1")

In [137]:
env.reset()

0

In [138]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
q_table = np.zeros((state_space_size,action_space_size))

In [139]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.3
discount_rate = 0.99
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001


In [140]:
rewards_from_all_episodes = []

# Q-Learning algorithm

for episode in range(num_episodes):
    state = env.reset() # resets the state of the environment back to the starting state.
    done = False
    rewards_current_episode=0
    
    for step in range(max_steps_per_episode):
        #Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if (exploration_rate_threshold > exploration_rate):
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
        
        new_state,reward,done,info = env.step(action)
        
        q_table[state,action] =q_table[state,action] * (1-learning_rate) + learning_rate * (reward+discount_rate* np.max(q_table[new_state,:])) 
                         
        state = new_state
        rewards_current_episode += reward
        if (done == True):
            break
        
    
    exploration_rate = min_exploration_rate + (max_exploration_rate -min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    rewards_from_all_episodes.append(rewards_current_episode)

rewards_per_thousand_episodes = np.split(np.array(rewards_from_all_episodes),num_episodes/1000)                          
count = 1000
                         
print(" ****** Average reward per thousand episodes ********")
for r in rewards_per_thousand_episodes:
    print(count,":",str(sum(r/1000)))
    count+=1000
      
# Print updated Q-table
print("********* Q-Table *********")
print(q_table)
                         
                         
                         
                         
                         
                         
                         
                         

 ****** Average reward per thousand episodes ********
1000 : 0.05000000000000004
2000 : 0.16000000000000011
3000 : 0.35900000000000026
4000 : 0.5110000000000003
5000 : 0.5670000000000004
6000 : 0.6440000000000005
7000 : 0.6300000000000004
8000 : 0.6450000000000005
9000 : 0.6300000000000004
10000 : 0.6600000000000005
********* Q-Table *********
[[0.54767093 0.45516909 0.45304147 0.45550406]
 [0.3999747  0.24205767 0.11861968 0.45165157]
 [0.32440625 0.27542828 0.26732328 0.37389783]
 [0.13387531 0.30402143 0.17656325 0.36610716]
 [0.58616949 0.44210237 0.35360109 0.31063876]
 [0.         0.         0.         0.        ]
 [0.0070713  0.00944692 0.22192657 0.00956196]
 [0.         0.         0.         0.        ]
 [0.32071929 0.40984669 0.40656113 0.6442262 ]
 [0.31037082 0.79221948 0.12436397 0.32468526]
 [0.85756123 0.35462469 0.34436696 0.1306398 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.45726353 0.10421705 0.82871366 0.155164

In [141]:
env.reset()
for episode in range(3):
    state = env.reset()
    done = False
    print ( " ******EPISODE" , episode+1,"*******\n\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])
        new_state , reward,done,info = env.step(action)

        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print(" You reached the goal !! ")
                time.sleep(1)

            else:
                print(" you fell through a hole !! ")
                time.sleep(3)
                clear_output(wait=True)
                break

        state = new_state
        
env.close()

 you fell through a hole !! 
your reward: 
0.0
