In [46]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [47]:
env=gym.make("FrozenLake-v1")

In [48]:
env.reset()

0

In [49]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
q_table = np.zeros((state_space_size,action_space_size))

In [50]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001


In [51]:
rewards_from_all_episodes = []

# Q-Learning algorithm

for episode in range(num_episodes):
    state = env.reset() # resets the state of the environment back to the starting state.
    done = False
    rewards_current_episode=0
    
    for step in range(max_steps_per_episode):
        #Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if (exploration_rate_threshold > exploration_rate):
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
        
        new_state,reward,done,info = env.step(action)
        
        q_table[state,action] =q_table[state,action] * (1-learning_rate) + (learning_rate * (reward+(discount_rate* np.max(q_table[new_state,:]))))
                         
        state = new_state
        rewards_current_episode += reward
        if (done == True):
            break
        
    
    exploration_rate = min_exploration_rate + (max_exploration_rate -min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    rewards_from_all_episodes.append(rewards_current_episode)

rewards_per_thousand_episodes = np.split(np.array(rewards_from_all_episodes),num_episodes/1000)                          
count = 1000
                         
print(" ****** Average reward per thousand episodes ********")
for r in rewards_per_thousand_episodes:
    print(count,":",str(sum(r/1000)))
    count+=1000
      
# Print updated Q-table
print("********* Q-Table *********")
print(q_table)
                         
                         
                         
                         
                         
                         
                         
                         

 ****** Average reward per thousand episodes ********
1000 : 0.04900000000000004
2000 : 0.20900000000000016
3000 : 0.4020000000000003
4000 : 0.5710000000000004
5000 : 0.6610000000000005
6000 : 0.6780000000000005
7000 : 0.6860000000000005
8000 : 0.6850000000000005
9000 : 0.7080000000000005
10000 : 0.6930000000000005
********* Q-Table *********
[[0.57547981 0.50452443 0.5044512  0.50792499]
 [0.35968119 0.34498412 0.29777182 0.52023461]
 [0.42215809 0.42881439 0.40947369 0.46972264]
 [0.27228999 0.32267523 0.37956316 0.44587805]
 [0.58996375 0.45124384 0.40711272 0.30950657]
 [0.         0.         0.         0.        ]
 [0.15273662 0.14257825 0.31586357 0.16164692]
 [0.         0.         0.         0.        ]
 [0.41166764 0.40254489 0.49816637 0.61717804]
 [0.44252708 0.65991698 0.2754386  0.35736492]
 [0.57893415 0.36972258 0.38836972 0.26372719]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.47810473 0.56957952 0.77489475 0.4590434